Created Angular project.
Kappathic/SEII-Instaclone pull request #9
Opened 2021-03-18 10:08 UTC by Kappathic

2021-03-19 12:28 UTC, Andi-Code requested changes
Entferne die .idea Ordner oder füge ein .gitignore in top level wo die .idea nicht mit commitet

2021-03-22 12:19 UTC, Kappathic reviewed
Deleted files & edited .gitignore @Andi-Code

2021-03-25 10:07 UTC, Kappathic reviewed
Required changes done.

2021-03-26 13:21 UTC, NKJN01 approved these changes
Beside that typo "Gregor Bertram" instead of "Bregor Gertram" everything looks fine

2021-03-26 13:22 UTC, merged